//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.28 at 11:41:07 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bancocoquimbo.com/xml/BancoCoquimbo")
package com.davivienda.api.schemas.bancocoquimbo;
