
package com.bancocoquimbo.xml.bancocoquimbo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BancoCoquimbo_HTTP_Service", targetNamespace = "http://www.bancocoquimbo.com/xml/BancoCoquimbo", wsdlLocation = "file:/home/andres/Documents/Project-Mbaas-Full/BancoCoquimbo/BancoCoquimbo-war/src/conf/xml-resources/web-services/ServiceWebCreationsUsers/wsdl/BancoCoquimbo.wsdl")
public class BancoCoquimboHTTPService
    extends Service
{

    private final static URL BANCOCOQUIMBOHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANCOCOQUIMBOHTTPSERVICE_EXCEPTION;
    private final static QName BANCOCOQUIMBOHTTPSERVICE_QNAME = new QName("http://www.bancocoquimbo.com/xml/BancoCoquimbo", "BancoCoquimbo_HTTP_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/andres/Documents/Project-Mbaas-Full/BancoCoquimbo/BancoCoquimbo-war/src/conf/xml-resources/web-services/ServiceWebCreationsUsers/wsdl/BancoCoquimbo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANCOCOQUIMBOHTTPSERVICE_WSDL_LOCATION = url;
        BANCOCOQUIMBOHTTPSERVICE_EXCEPTION = e;
    }

    public BancoCoquimboHTTPService() {
        super(__getWsdlLocation(), BANCOCOQUIMBOHTTPSERVICE_QNAME);
    }

    public BancoCoquimboHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANCOCOQUIMBOHTTPSERVICE_QNAME, features);
    }

    public BancoCoquimboHTTPService(URL wsdlLocation) {
        super(wsdlLocation, BANCOCOQUIMBOHTTPSERVICE_QNAME);
    }

    public BancoCoquimboHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANCOCOQUIMBOHTTPSERVICE_QNAME, features);
    }

    public BancoCoquimboHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoCoquimboHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BancoCoquimboPortType
     */
    @WebEndpoint(name = "BancoCoquimbo_Port")
    public BancoCoquimboPortType getBancoCoquimboPort() {
        return super.getPort(new QName("http://www.bancocoquimbo.com/xml/BancoCoquimbo", "BancoCoquimbo_Port"), BancoCoquimboPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoCoquimboPortType
     */
    @WebEndpoint(name = "BancoCoquimbo_Port")
    public BancoCoquimboPortType getBancoCoquimboPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bancocoquimbo.com/xml/BancoCoquimbo", "BancoCoquimbo_Port"), BancoCoquimboPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANCOCOQUIMBOHTTPSERVICE_EXCEPTION!= null) {
            throw BANCOCOQUIMBOHTTPSERVICE_EXCEPTION;
        }
        return BANCOCOQUIMBOHTTPSERVICE_WSDL_LOCATION;
    }

}
